config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :friends
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "articles#index"
  resource :session
  resource :registration
  resource :password_reset
  resource :password
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :articles do
    resources :comments
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	include Visible
	has_many :comments, dependent: :destroy

	validates :owner_id, presence: true
	validates :title, presence: true, length: { maximum: 10 }
 	validates :body, presence: true, length: { minimum: 10 }


end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :article

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
  
  validates :username, uniqueness: { message: "Username Already Taken", case_sensitive: false }
	validates :email, presence: true, uniqueness: { message: "Email Already Used", case_sensitive: false }
	normalizes :email, with: -> (email) {email.strip.downcase}

	generates_token_for :password_reset, expires_in: 15.minutes do
		password_salt(10)
	end

	generates_token_for :email_confirmation, expires_in: 24.hours do
		email
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_current_user, if: :user_signed_in?	
	private

	def authenticate_user!
		redirect_to root_path, alert: "You must be logged in to do that" unless user_signed_in?
	end

	
	def set_current_user
		Current.user = current_user
	end

	def current_user
		Current.user ||= authenticate_user_from_session
	end

	helper_method :current_user

	def authenticate_user_from_session
		User.find_by(id: session[:user_id])
	end	

	def user_signed_in?
		current_user.present?
	end

	helper_method :user_signed_in?



	def login(user)
		Current.user = user
		reset_session
		session[:user_id] = user.id
		session[:username] = user.username
	end

	def logout(user)
		Current.user = nil
		reset_session
	end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    unless user_signed_in?
      redirect_to new_session_path 
    end

    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
    unless user_signed_in? && session[:user_id] == @article.owner_id
      redirect_to root_path
      flash[:alert] = "You are not the owner of this Article"
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    unless user_signed_in? && session[:user_id] == @article.owner_id
      redirect_to root_path
      flash[:alert] = "You are not the owner of this Article"
    else

    @article.destroy
    redirect_to root_path, status: :see_other

    end
  end

  private
  def article_params
    params.require(:article).permit(:owner_id,:title,:body,:status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



  def create
    @article = Article.find(params[:article_id])  
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

 def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
 end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter_id, :body, :status)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :set_user_by_token, only: [:edit,:update]
	def new
	end

	def create
		if (user = User.find_by(email: params[:email]))
			PasswordMailer.with(
				user: :user,
				token: user.generate_token_for(:password_reset)
				).password_reset.deliver_later
		end

		redirect_to root_path, notice: "Check your email to reset your password"
	end

	def edit
	end

	def update
		if @user.update(password_params)
			redirect_to new_session_path, notice: "Your password has been reset succesfully. please login"
		else
			render :edit, status: :unprocessable_entity
		end
	end

	private
	def password_params
		params.require(:user).permit(:password, :password_confirmation)
	end
	def set_user_by_token
		@user = User.find_by_token_for(:password_reset, params[:token])
		redirect_to new_password_resets_path alert:"invalid token, please try again." unless @user.present?
	end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	before_action :authenticate_user!

	def edit
	end

	def update
		if current_user.update(password_params)
			redirect_to edit_password_path, notice: "Your password has been updated succesfully"
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def password_params
		params.require(:user).permit(
			:password,
			:password_confirmation,
			:password_challenge
			).with_defaults(password_challenge:"")
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

def new
  @user = User.new
end

def create 
      @user = User.new(registration_params)
      if @user.save
        login @user
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
end

private
  def registration_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		if user = User.authenticate_by(email: params[:email],password:params[:password])
			login user
			redirect_to root_path, notice: "You have signed succesfully"
		else
			flash[:alert] = "Invalid email or password"
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		logout current_user
		redirect_to root_path, notice: "You Have been logged out"
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
 

	def show
     @user = User.find(session[:user_id])

	end
	def edit
      @user = User.find(session[:user_id])
 	end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user

    flash[:alert] = "You need to login again"
       reset_session
    else
      render :edit, status: :unprocessable_entity
    end
 
  end




  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/application/_header.html.erb
<nav>
  <ul class="navbar">
    <li class="menu"><div class="normal"><a href="<%=root_path%>"><%= render 'text-anim' %></div></a></li>
  
    <% if user_signed_in? %>
   <li class="normal"> 
    <% username =session[:username]%>
    <%= link_to username, current_user%></li>
    <% else %>
     <li class="normal"> 
    <%= link_to "Guest",root_path%></li>
    <% end %>
    <%= render "user"%> 
  </ul>
</nav> 

app/views/application/_text-anim.html.erb
<div class="animation">
	<% text = ["T","e","s"," ","W","e","b"]%>
	<% text.each do |isi|%><span class="isi"><%=isi%></span><%end %><span class="garis">|</span>
</div>

app/views/application/_user.html.erb
<% if user_signed_in? %>
      <li class="normal"><%= link_to "Edit Password", edit_password_path %></li>
      <li class="normal "> <%= button_to "Log Out", session_path,class: "button" ,method: :delete %></li>
      <% else %>
        <li class="normal"> <%= link_to "Sign Up", new_registration_path %></li>
        <li class="normal">  <%= link_to "Log In", new_session_path %> </li>
      <% end %>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <p>
    <% if session[:username] != nil %>
    <%= form.text_field :owner_id, value:session[:user_id],:readonly => true, :type => "hidden"%>
    <% end %>
  </p>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body ,class:"article-content"%><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
</div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_header.html.erb
<nav>
  <ul class="navbar">
    <li class="menu"><div class="normal"><a href="<%=root_path%>"><%= render 'text-anim' %></div></a></li>
    <li ><%= Article.public_count %></li>
   <li > Services</li>
  </ul>
</nav> 

app/views/articles/edit.html.erb
<div class="body-content">
<h4>Edit Article</h4>

<%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<div class="content">
	<table class="normal list big-font">
		<%index = 0%>
	<tr>
		<th>No</th>
		<th>Article</th>
		<th>Owner</th>
		<th>Description</th>
		<th>Action</th>
	</tr>	
	<% @articles.each do |article| %>
	 <% unless article.archived? %>
	 <%index = index+1%>
	<tr>
		<td><%=index%></td>
		<td class="column-med"><%=article.title%></br></td>
		<td class="column-small"><%=User.find(article.owner_id).username%></td>
		<td class="column-med"><%= article.body%></td>
		<td class="column-small"><%= link_to "Show", article%>
			
			<%= link_to "Edit", edit_article_path(article)%> 
			 <%= link_to "Destroy", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
	</tr>
	<% end %>
	<% end %>
	</table>
</div>
<p class="normal left_padded">
<%= link_to "New Article", new_article_path %>

</p>

app/views/articles/new.html.erb
<h4>New Article</h4>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="show-content">


  <div class="body-content">
    <div class="title">
  <h3>Title: <%= @article.title %></h3>
  <h4>Owner: <%= User.find(@article.owner_id).username %></h4>
</div>
  <p><%= @article.body %></p>



  <ul>
    <% if session[:user_id] == @article.owner_id %>
      
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

    <% end %>
</div>
<div class="comment-content">
<div class="comment">
<h3>Comments</h3>
<%= render @article.comments %> 
</div>
<% if user_signed_in? %>
  
<div class="add_comment">
<h4>Add a comment:</h4>
<%= render 'comments/form' %>
</div>
<% end %>
</div>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
  <strong>Commenter:</strong>
  <%= User.find(comment.commenter_id).username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<%if session[:user_id] == comment.commenter_id%>
<p>
<%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% else %>

hello

<% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <% if session[:username] != nil %>
    <%= form.text_field :commenter_id, value:session[:user_id],:readonly => true, :type => "hidden"%>
    <% end %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "turbo", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    
    <div data-theme="dark">
    <%= render "header"%>
    <div><%=notice%></div>
    <div><%=alert%></div>
    
    
    <%= yield %>
    

 
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h4>Reset Password</h4>
<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
     <% form.object.errors.full_messages.each do |messages|%>
         <div><% message %></div>
     <%end%>
    <%end%>


    <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    </div>

    <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    </div>

    <div>
        <%= form.submit "Reset password" %>
    </div>
<%end%>

app/views/password_resets/new.html.erb
<%= form_with model: @user, url: session_path do |form| %>
    

    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>

    <div>
        <%= form.submit "Reset Password"%>
    </div>
<% end %>

app/views/users/edit.html.erb
<div class="show-content">


  <div class="body-content">
    <div class="title">
  <h3>Edit User Info</h3>
    </div>
    <%= form_with model: current_user do |form| %>
    <% if form.object.errors.any? %>
     <% form.object.errors.full_messages.each do |message|%>
         <div><%= message %></div>
     <%end%>
    <%end%>

    <div>
    <%= form.label :username, "Username"%><br>
    <%= form.text_field :username%>
    </div>

    <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    </div>


    <div>
        <%= form.submit "Edit" %>
    </div>
<%end%>




</div>

</div>

app/views/users/show.html.erb
<div class="show-content">


  <div class="body-content">
    <div class="title">
  <h3>User Info</h3>
    </div>

    <p><span class="bold">Email</span><br><%= User.find(session[:user_id]).email %></p>

  <p><span class="bold">Username</span><br><%= User.find(session[:user_id]).username %></p>

<div class="normal">
<%= link_to "Edit", edit_user_path(@user),class: "normal" %> 
</div>
</div>

</div>